import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Minus,Plus,ShoppingCart,Trash2,Lock,Loader2,AlertCircle,UserRound} from 'lucide-react';
import {supabase,getSettings,taka} from '../lib/supabase';
import PaymentQR from '../components/PaymentQR';
import {subscriptionDurationLabel} from '../lib/subscription';
import useTitle from '../lib/useTitle';import {trackInitiateCheckout} from '../lib/metaPixel';

const KEY='stationery_cart_v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const save=x=>{localStorage.setItem(KEY,JSON.stringify(x));window.dispatchEvent(new Event('stationery-cart-change'));};
export function getCart(){return read();}
export function addToCart(item){const c=read();const i=c.findIndex(x=>x.id===item.id);if(i>=0)c[i]={...c[i],quantity:Math.min(100000,(c[i].quantity||1)+1)};else c.push({...item,quantity:1});save(c);}
export function removeFromCart(id){save(read().filter(x=>x.id!==id));}
export function cartCount(){return read().reduce((n,x)=>n+(Number(x.quantity)||1),0);}

const Fld=({l,children})=><label className="fld"><span>{l}</span>{children}</label>;
const OK=['image/jpeg','image/png','image/webp','application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
const MIME={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',pdf:'application/pdf',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};
const ct=x=>OK.includes(x.type)?x.type:MIME[x.name.split('.').pop().toLowerCase()];

export default function Cart(){
 useTitle('Cart');const nav=useNavigate();const[items,setItems]=useState(read);const[settings,setSettings]=useState({});const[f,setF]=useState({customer_name:'',phone:'',whatsapp:'',email:'',method:'',transaction_id:''});const[files,setFiles]=useState([]);const[proof,setProof]=useState(null);const[paid,setPaid]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState('');
 useEffect(()=>{const sync=()=>setItems(read());window.addEventListener('storage',sync);window.addEventListener('stationery-cart-change',sync);getSettings().then(setSettings).catch(()=>{});supabase.auth.getSession().then(({data})=>{const u=data.session?.user;if(u)setF(v=>({...v,customer_name:u.user_metadata?.full_name||u.user_metadata?.name||'',email:u.email||''}));});return()=>{window.removeEventListener('storage',sync);window.removeEventListener('stationery-cart-change',sync)}},[]);
 const fixed=items.filter(x=>Number(x.price)>0);const quote=items.filter(x=>Number(x.price)<=0);const total=fixed.reduce((s,x)=>s+Number(x.price)*(Number(x.quantity)||1),0);
 const methods=settings.payment_qr_url?[{name:'Bangla QR',number:'Scan the QR to pay',qr:settings.payment_qr_url}]:[];
 const selected=methods.find(x=>x.name===f.method)||methods[0];
 const changeQty=(id,n)=>{const q=Math.min(100000,Math.max(1,n||1));const c=read().map(x=>x.id===id?{...x,quantity:q}:x);save(c);setItems(c)};
 function pick(e){const l=[...e.target.files];if(l.length>5)return setErr('Max 5 files');for(const x of l){if(!ct(x))return setErr('Allowed: jpg, png, webp, pdf, doc, docx');if(x.size>10*1024*1024)return setErr('Each file must be under 10MB')}setErr('');setFiles(l);}
 function pickProof(e){const x=e.target.files?.[0];if(!x){setProof(null);return}if(!['image/jpeg','image/png','image/webp'].includes(x.type))return setErr('Payment screenshot must be JPG, PNG or WEBP');if(x.size>5*1024*1024)return setErr('Payment screenshot must be 5MB or smaller');setErr('');setProof(x);}
 async function submit(e){e.preventDefault();setErr('');if(!items.length)return;const ph=f.phone.replace(/\D/g,'');if(f.customer_name.trim().length<2)return setErr('Enter your name');if(fixed.some(x=>x.requires_file)&&files.length===0)return setErr('Please upload the required documents for your cart items');if(!/^(880|0)?1\d{9}$/.test(ph))return setErr('Enter a valid Bangladeshi mobile number');if(!methods.length)return setErr('The store has not configured Bangla QR payment yet.');if(!proof)return setErr('Upload a screenshot of your successful payment');if(!paid)return setErr('Please confirm that you have completed the payment');setBusy(true);trackInitiateCheckout({contentIds:fixed.map(x=>x.id),value:total,numItems:fixed.reduce((n,x)=>n+(Number(x.quantity)||1),0)});let proofPath='';const created=[];try{const ext=proof.name.split('.').pop().toLowerCase();proofPath=`uploads/cart-payproof-${crypto.randomUUID()}.${ext}`;let r=await supabase.storage.from('order-files').upload(proofPath,proof,{contentType:proof.type});if(r.error)throw r.error;const up=[];for(const x of files){const path=`uploads/${crypto.randomUUID()}-${x.name.replace(/[^\\w.\\-]/g,'_')}`;r=await supabase.storage.from('order-files').upload(path,x,{contentType:ct(x)});if(r.error)throw r.error;up.push({path,name:x.name});}
 const{data:codes,error}=await supabase.rpc('create_cart_orders',{p:{customer_name:f.customer_name,phone:f.phone,whatsapp:f.whatsapp,email:f.email,method:selected.name,payment_proof_path:proofPath,items:fixed.map(x=>({package_id:x.id,quantity:Number(x.quantity)||1,files:up,notes:''}))}});if(error)throw error;
 localStorage.removeItem(KEY);window.dispatchEvent(new Event('stationery-cart-change'));nav('/order-success/'+codes[0]+'?cart='+encodeURIComponent(codes.join(','))+'&value='+encodeURIComponent(total)+'&items='+encodeURIComponent(fixed.map(x=>x.id).join(',')));
 }catch(x){setErr(x.message||'Could not place the cart orders. Please try again.');}finally{setBusy(false)}}
 if(!items.length)return <main className="wrap"><section className="card empty"><ShoppingCart size={30}/><h1>Your cart is empty</h1><p className="muted">Add multiple packages here, then place them together.</p><Link className="btn" to="/services">Browse services</Link></section></main>;
 return <main className="wrap"><div className="crumbs"><Link to="/services">Services</Link> / Cart</div><h1>Your cart</h1><p className="muted">Add several packages and submit them together in one checkout.</p>
 <div className="cart-layout"><section><div className="card cart-list">{items.map(x=><article className="cart-item" key={x.id}><div><b>{x.name}</b><span>{x.service_name}</span>{x.access_type&&<small>{x.access_type==='shared'?'Shared':'Personal'} · {subscriptionDurationLabel(x.duration_months)}</small>}</div><div className="cart-item-actions"><div className="qty"><button type="button" onClick={()=>changeQty(x.id,(Number(x.quantity)||1)-1)}><Minus size={15}/></button><input value={x.quantity} onChange={e=>changeQty(x.id,Number(e.target.value.replace(/\D/g,''))||1)}/><button type="button" onClick={()=>changeQty(x.id,(Number(x.quantity)||1)+1)}><Plus size={15}/></button></div><strong>{Number(x.price)>0?taka(Number(x.price)*(Number(x.quantity)||1)):'Price on request'}</strong><button type="button" className="icon-btn" aria-label="Remove" onClick={()=>removeFromCart(x.id)}><Trash2 size={17}/></button></div></article>)}</div>
 {quote.length>0&&<div className="card" style={{marginTop:16}}><b>Price-on-request items</b><p className="muted">These items need a separate price discussion, so they are not included in the paid cart checkout.</p></div>}</section>
 <form className="checkout" onSubmit={submit}><section className="card sec"><h2 className="sech"><span className="num">1</span>Your details</h2><p className="account-checkout-note"><UserRound size={16}/> You can sign in before checkout to keep these orders in your account.</p><div className="two"><Fld l="Full name *"><input value={f.customer_name} onChange={e=>setF({...f,customer_name:e.target.value})}/></Fld><Fld l="Mobile number *"><input inputMode="tel" placeholder="01XXXXXXXXX" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></Fld><Fld l="WhatsApp number"><input value={f.whatsapp} onChange={e=>setF({...f,whatsapp:e.target.value})}/></Fld><Fld l="Email (optional)"><input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></Fld></div></section>
 <section className="card sec" style={{marginTop:16}}><h2 className="sech"><span className="num">2</span>Files</h2><div className="drop"><b>Attach files (optional)</b><p className="muted">Files are attached to each paid cart order.</p><input type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx" onChange={pick}/>{files.length>0&&<ul className="files">{files.map(x=><li key={x.name}>{x.name}</li>)}</ul>}</div></section>
 <section className="card sec" style={{marginTop:16}}><h2 className="sech"><span className="num">3</span>Payment</h2>{selected&&<PaymentQR settings={settings} total={total} method={selected}/>}<div className="two"><Fld l="Payment screenshot *"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={pickProof}/></Fld><Fld l="Payment method *"><input value={selected?.name||'Bangla QR'} readOnly/></Fld></div><label style={{display:'flex',gap:10,alignItems:'flex-start',fontWeight:500}}><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/> I have completed the payment</label></section>
 <aside className="card summary"><h3>Cart total</h3><div className="ln tot"><dt>Total</dt><dd>{taka(total)}</dd></div>{err&&<p className="err" role="alert"><AlertCircle size={16}/>{err}</p>}<button className="btn lg block" disabled={busy||!fixed.length}>{busy?<><Loader2 size={18}/>Placing orders…</>:<><Lock size={16}/>Place {fixed.length} order{fixed.length===1?'':'s'} together</>}</button><p className="muted" style={{marginTop:10}}>One payment proof is used for the cart orders.</p></aside></form></div></main>;
}