import {useEffect,useState} from 'react';import {Link,useNavigate} from 'react-router-dom';import {ArrowRight,Search,QrCode,PackageSearch,Upload,ShieldCheck,Headphones,Layers,CreditCard,MousePointerClick,ListChecks,Truck} from 'lucide-react';
import {supabase,getSettings} from '../lib/supabase';import {CATEGORIES} from '../data/services';import ServiceCard from '../components/ServiceCard';import {catStyle} from '../components/ServiceCover';import useTitle from '../lib/useTitle';import {waLink} from '../lib/whatsapp';
export default function Home(){useTitle('Digital, Travel & Meta Solution Hub','Order document services, Meta ads, social media growth, digital subscriptions and creative design online in Bangladesh. Pay and track your order.');
const nav=useNavigate();const[pop,setPop]=useState(null);const[q,setQ]=useState('');const[settings,setSettings]=useState({});
useEffect(()=>{getSettings().then(setSettings);(async()=>{const sel='*,packages(price,is_active)';let r=await supabase.from('services').select(sel).eq('is_active',true).eq('is_popular',true).limit(6);if(!r.data?.length)r=await supabase.from('services').select(sel).eq('is_active',true).order('sort_order').limit(6);setPop(r.data||[]);})();},[]);
return(<>{settings.announcement&&<div className="announcement">{settings.announcement}</div>}<section className="hero"><div className="wrap in"><div><span className="eyebrow">{settings.site_tagline||'Dhaka · Digital, document &amp; social media services'}</span><h1>{settings.hero_title||'One place for your'} <em>{settings.hero_highlight||'digital, travel & Meta'}</em> {settings.hero_title?'':'needs'}</h1><p className="lead">{settings.hero_description||'Choose a service, pick a package, upload documents, pay and track your order online. Our Fakirapool office is here if you need help.'}</p>
<form className="search" role="search" onSubmit={e=>{e.preventDefault();nav('/services?q='+encodeURIComponent(q));}} style={{maxWidth:500,marginTop:20}}><Search size={18}/><input aria-label="Search services" placeholder="Search e.g. Passport, Canva Pro, Facebook Ads" value={q} onChange={e=>setQ(e.target.value)}/></form>
<div className="row" style={{marginTop:18}}><Link className="btn lg" to="/services">Browse Services <ArrowRight size={18}/></Link><Link className="btn lg ghost" to="/track-order">Track Order</Link></div>
<div className="trust"><span><Upload size={16}/>Private document uploads</span><span><QrCode size={16}/>Pay by QR</span><span><ShieldCheck size={16}/>Order tracking</span></div></div>
<div className="mosaic">{CATEGORIES.map(c=>{const s=catStyle(c.name);const I=s.I;return(<Link key={c.name} className="tile" to={`/services?category=${encodeURIComponent(c.name)}`}><span className="ti" style={{background:s.bg,color:s.fg}}><I size={22}/></span><b>{c.name}</b></Link>);})}</div></div></section>
<main className="wrap" style={{paddingTop:0}}>
<section className="sect"><div className="head"><div><h2>Browse by category</h2><p className="sub">Five service areas, one account-free ordering flow.</p></div></div><div className="grid">{CATEGORIES.map(c=>{const s=catStyle(c.name);const I=s.I;return(<Link key={c.name} className="catcard" to={`/services?category=${encodeURIComponent(c.name)}`}><div className="cathead" style={{background:s.bg,color:s.fg}}><span className="ci"><I size={28}/></span><span className="n">{c.items.length} services</span></div><div className="catbody"><h3>{c.name}</h3><p className="muted">{c.items.slice(0,3).join(' · ')}</p><span style={{color:'var(--g)',fontWeight:700,display:'inline-flex',gap:4}}>Explore <ArrowRight size={16}/></span></div></Link>);})}</div></section>
<section className="sect"><div className="head"><div><h2>Featured services</h2><p className="sub">Packages with clear prices.</p></div><Link className="btn alt sm" to="/services">View all</Link></div>{pop===null?<div className="grid">{[1,2,3].map(i=><div className="sk" style={{height:300}} key={i}/>)}</div>:pop.length?<div className="grid">{pop.map(s=><ServiceCard key={s.id} s={s}/>)}</div>:<div className="card empty">Services will appear here once added.</div>}</section>
<section className="sect"><div className="head"><div><h2>Why choose Stationery Dot Com</h2></div></div><div className="grid">{[[Layers,'One place for everything','Digital, travel/document and social media support under one roof.'],[MousePointerClick,'Simple online ordering','Pick a package and check out in a few steps, on mobile or desktop.'],[PackageSearch,'Order tracking','Follow your order with your Order ID and phone number.'],[Headphones,'Direct support','Call, WhatsApp or visit us at G-Nat Tower, Fakirapool.']].map(([I,t,d])=><div className="card" key={t}><div className="ico"><I size={22}/></div><h3>{t}</h3><p className="muted" style={{margin:0}}>{d}</p></div>)}</div></section>
<section className="sect"><div className="head"><div><h2>How it works</h2></div></div><div className="steps5">{[[Search,'Browse','Explore categories and services.'],[ListChecks,'Select service','Compare packages and prices.'],[MousePointerClick,'Place order','Add details and documents.'],[CreditCard,'Pay','Scan the QR and enter your Transaction ID.'],[Truck,'Track','Follow progress with your Order ID.']].map(([I,t,d],i)=><div className="st" key={t}><div className="n">{i+1}</div><b style={{display:'flex',gap:6,alignItems:'center'}}><I size={16}/>{t}</b><p className="muted" style={{margin:'4px 0 0'}}>{d}</p></div>)}</div></section>
<section className="sect"><div className="cta"><div><h2>Ready to place your order?</h2><p>Start online, or talk to us first. We will help you choose.</p></div><div className="row"><Link className="btn lg" to="/services">Order Now</Link><a className="btn lg wa" href={waLink()}>WhatsApp Us</a></div></div></section></main></>);}
