import {useEffect,useMemo,useState} from 'react';import {Link,useNavigate,useSearchParams} from 'react-router-dom';import {ArrowRight,Clock3,Globe2,Heart,Search,ShieldCheck,Users,WalletCards,Zap} from 'lucide-react';import {getSettings,supabase,taka} from '../lib/supabase';import useTitle from '../lib/useTitle';import '../smm.css';import '../smm-wallet.css';import '../smm-brand.css';import {trackPurchase} from '../lib/metaPixel';
const platforms=['All platforms','Facebook','Instagram','TikTok','YouTube','Telegram','X / Twitter'];const kinds=['All services','Followers','Likes','Reactions','Comments','Views','Shares','Subscribers','Members','Reviews','Watch Time'];
export default function SmmPanel(){useTitle('SMM Panel Services','Choose social media growth services and order online.');const[list,setList]=useState(null),[loadError,setLoadError]=useState(false),[settings,setSettings]=useState({}),[q,setQ]=useState(''),[platform,setPlatform]=useState(platforms[0]),[kind,setKind]=useState(kinds[0]),[country,setCountry]=useState('All locations'),[selected,setSelected]=useState(null),[qty,setQty]=useState(''),[session,setSession]=useState(null),[balance,setBalance]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[showMore,setShowMore]=useState(false);const nav=useNavigate(),[sp]=useSearchParams();const user=session?.user;const profileName=user?.user_metadata?.full_name||user?.user_metadata?.name||'';async function loadBalance(){const{data,error}=await supabase.rpc('get_smm_wallet');if(!error)setBalance(Number(data||0));else setBalance(null);}useEffect(()=>{supabase.from('services').select('id,category,name,description,is_active,sort_order,smm_platform,smm_category,smm_country,smm_service_code,smm_min_quantity,smm_max_quantity,smm_price_per_1000,smm_start_time,smm_delivery_time,smm_refill,smm_cancel,smm_instructions').eq('is_active',true).order('sort_order').then(({data,error})=>{setLoadError(Boolean(error));setList((data||[]).filter(s=>s.smm_platform||s.category==='SMM Panel Services'));});getSettings().then(setSettings);supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadBalance();});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,next)=>{setSession(next);if(next)setTimeout(loadBalance,0);else setBalance(null);});return()=>subscription.unsubscribe();},[]);useEffect(()=>{const id=sp.get('service');if(id&&list){const s=list.find(x=>x.id===id);if(s){setSelected(s);setQty(String(s.smm_min_quantity||''));}}},[sp,list]);const visible=useMemo(()=>{const text=q.trim().toLowerCase();return(list||[]).filter(s=>(!text||`${s.name} ${s.description||''} ${s.smm_service_code||''}`.toLowerCase().includes(text))&&(platform===platforms[0]||s.smm_platform===platform)&&(kind===kinds[0]||s.smm_category===kind)&&(country==='All locations'||s.smm_country===country));},[list,q,platform,kind,country]);useEffect(()=>setShowMore(false),[q,platform,kind,country]);const displayed=showMore?visible:visible.slice(0,9);const total=selected?Number(((Number(qty)||0)*Number(selected.smm_price_per_1000||0)/1000).toFixed(2)):0;
function beginOrder(s){if(!session){nav('/account?next='+encodeURIComponent(`/smm?service=${s.id}`));return;}setSelected(s);setQty(String(s.smm_min_quantity||''));setMessage('');}async function submit(e){e.preventDefault();setMessage('');if(!session){nav('/account?next='+encodeURIComponent(`/smm?service=${selected?.id}`));return;}const form=new FormData(e.currentTarget),amount=Number(qty),link=String(form.get('link')||'').trim(),phone=String(form.get('phone')||'').trim(),name=String(form.get('name')||'').trim();if(!selected||amount<selected.smm_min_quantity||amount>selected.smm_max_quantity)return setMessage(`Enter a quantity from ${selected.smm_min_quantity} to ${selected.smm_max_quantity}.`);if(!/^https?:\/\//i.test(link))return setMessage('Enter the public profile, post, or channel link.');if(total>Number(balance||0))return setMessage('Your wallet balance is too low. Add funds from your account wallet first.');if(!form.get('agree'))return setMessage('Please accept the service rules.');setBusy(true);const payload={service_id:selected.id,customer_name:name,phone,email:session.user.email||'',quantity:amount,target_link:link,notes:String(form.get('notes')||'')};const{data,error}=await supabase.rpc('create_smm_order',{p:payload});setBusy(false);if(error)return setMessage(error.message.includes('function')?'Wallet database update is not installed yet. Please contact support.':error.message);trackPurchase({orderId:data,contentIds:[selected.id],value:total,numItems:amount});setSelected(null);nav(`/order-success/${encodeURIComponent(data)}?wallet=1&value=${encodeURIComponent(total)}&items=${encodeURIComponent(selected.id)}`);}
return <><div className="smm-shell">
<section className="smm-topbar"><div className="smm-top-inner"><div><span className="smm-kicker"><Zap size={12}/> SMM MARKETPLACE</span><h1>Social Media Services</h1><p>Find the right service, check the details, and place your order from your wallet.</p></div><div className="smm-top-stats"><span><ShieldCheck size={14}/> Secure checkout</span><span><Clock3 size={14}/> Live service details</span></div></div></section>
<main className="smm-main" id="smm-services">
<div className="smm-catalog-head"><div><span className="smm-overline">SERVICE CATALOG</span><h2>Choose a service</h2></div><div className="smm-live-count">{list===null?'Loading…':`${visible.length} services available`}</div></div>
<div className="smm-platforms">{platforms.map(x=><button key={x} className={platform===x?'active':''} onClick={()=>setPlatform(x)}>{x}</button>)}</div>
<div className="smm-toolbar"><label className="smm-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search services, keywords or service ID"/></label><select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(x=><option key={x}>{x}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)}>{['All locations','Bangladesh','Worldwide','Mixed'].map(x=><option key={x}>{x}</option>)}</select></div>
{list===null?<div className="smm-list">{[1,2,3,4].map(i=><div className="smm-skeleton" key={i}/>)}</div>:loadError?<div className="smm-empty"><b>SMM catalogue is being prepared</b><p>The database update is needed before SMM services can appear.</p></div>:visible.length===0?<div className="smm-empty"><b>No matching services</b><p>Try another platform, service type or search term.</p><button className="btn alt sm" onClick={()=>{setQ('');setPlatform(platforms[0]);setKind(kinds[0]);setCountry('All locations');}}>Clear filters</button></div>:<><div className="smm-list">{displayed.map(s=><article className="smm-service-row" key={s.id}>
<div className="smm-service-main"><div className="smm-service-icon"><Users size={17}/></div><div className="smm-service-copy"><div className="smm-row-tags"><b>{s.smm_platform}</b><span>{s.smm_country||'Worldwide'}</span></div><h3>{s.name}</h3><p>{s.description||'Review the service information before ordering.'}</p></div></div>
<div className="smm-row-info"><span><small>MIN / MAX</small><b>{Number(s.smm_min_quantity||0).toLocaleString()} – {Number(s.smm_max_quantity||0).toLocaleString()}</b></span><span><small>DELIVERY</small><b>{s.smm_delivery_time||'—'}</b></span><span><small>REFILL</small><b>{s.smm_refill||'No'}</b></span></div>
<div className="smm-row-price"><small>PER 1,000</small><strong>{taka(s.smm_price_per_1000)}</strong></div>
<button className="smm-order-btn" onClick={()=>beginOrder(s)}>{session?'Order':'Sign in'} <ArrowRight size={14}/></button>
</article>)}</div>{visible.length>9&&<button className="smm-more" onClick={()=>setShowMore(v=>!v)}>{showMore?'Show less':`Show more ${visible.length-9} services`}</button>}</>}
<div className="smm-rules"><ShieldCheck size={16}/><p><b>Before ordering:</b> Keep the target profile/content public during delivery. Start and delivery times are estimates and refill/cancellation terms follow each service.</p></div>
</main></div>{selected&&</main>{selected&&<div className="smm-modal-back" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null);}}><section className="smm-modal" role="dialog" aria-modal="true" aria-labelledby="smm-order-title"><button className="smm-close" onClick={()=>setSelected(null)} aria-label="Close">×</button><span className="smm-overline">WALLET CHECKOUT</span><h2 id="smm-order-title">{selected.name}</h2><p className="muted">ID {selected.smm_service_code||'—'} · {selected.smm_platform} · {selected.smm_country}</p><div className="smm-modal-info">{selected.smm_instructions||'Submit a public link. Make sure the profile or content matches the chosen service.'}</div>{!session?<div className="smm-login-prompt"><b>Sign in to continue</b><p>Orders use your Stationery Dot Com account and wallet.</p><Link className="btn sm" to={`/account?next=${encodeURIComponent(`/smm?service=${selected.id}`)}`}>Sign in / create account <ArrowRight size={15}/></Link></div>:<form onSubmit={submit}><div className="smm-wallet-strip"><span><WalletCards size={16}/>Available wallet</span><b>{balance===null?'Loading…':taka(balance)}</b></div><label>Name<input name="name" defaultValue={profileName} required maxLength="120" autoComplete="name"/></label><label>Mobile number<input name="phone" required inputMode="tel" autoComplete="tel" placeholder="01XXXXXXXXX"/></label><label>Profile / post / channel link<input name="link" required type="url" placeholder="https://…"/></label><label>Quantity <small>({Number(selected.smm_min_quantity).toLocaleString()}–{Number(selected.smm_max_quantity).toLocaleString()})</small><input type="number" min={selected.smm_min_quantity} max={selected.smm_max_quantity} value={qty} onChange={e=>setQty(e.target.value)} required/></label><div className="smm-total"><span>Order total <small>Calculated and charged atomically on the server</small></span><b>{taka(total)}</b></div>{total>Number(balance||0)&&<div className="smm-insufficient">Insufficient balance. <Link to="/account#wallet">Add funds to your wallet</Link> before ordering.</div>}<label>Notes <small>(optional)</small><textarea name="notes" rows="2" maxLength="1000"/></label><label className="smm-consent"><input type="checkbox" name="agree" required/>I have read the service instructions and accept the listed delivery, refill and cancellation terms.</label>{message&&<p role="alert" className="err">{message}</p>}<button className="btn block" disabled={busy||balance===null||total>Number(balance||0)}>{busy?'Placing order…':'Confirm & place order'} <ArrowRight size={16}/></button></form>}</section></div>}</>;
}return <div className="smm-app">
<aside className="smm-sidebar"><div className="smm-brandmark"><span>S</span><div><b>Stationery</b><small>SMM MARKETPLACE</small></div></div>
<div className="smm-side-label">PLATFORMS</div><nav>{platforms.map((x,i)=><button key={x} className={platform===x?'active':''} onClick={()=>setPlatform(x)}><span className="smm-side-icon">{i===0?'✦':x==='Facebook'?'f':x==='Instagram'?'◎':x==='TikTok'?'♪':x==='YouTube'?'▶':x==='Telegram'?'➤':'𝕏'}</span>{x}</button>)}</nav>
<div className="smm-side-label">SERVICE TYPE</div><div className="smm-side-types">{kinds.slice(1,7).map(x=><button key={x} className={kind===x?'active':''} onClick={()=>setKind(kind===x?kinds[0]:x)}>{x}</button>)}</div>
<div className="smm-side-bottom"><ShieldCheck size={15}/><div><b>Secure ordering</b><small>Wallet protected checkout</small></div></div></aside>
<section className="smm-workspace"><header className="smm-commandbar"><div><span className="smm-command-kicker">SOCIAL MEDIA SERVICES</span><h1>Service Marketplace</h1></div><div className="smm-command-actions"><div className="smm-balance"><WalletCards size={15}/><span>Wallet</span><b>{balance===null?'—':taka(balance)}</b></div><Link className="smm-account-link" to="/account">My account <ArrowRight size={13}/></Link></div></header>
<main className="smm-content"><div className="smm-welcome"><div><span>MARKETPLACE</span><h2>What do you want to grow?</h2><p>Browse services by platform, compare delivery terms and order directly from your wallet.</p></div><div className="smm-live-pill"><i/> {list===null?'Loading catalogue':visible.length+' services live'}</div></div>
<div className="smm-quick-grid">
<button onClick={()=>setKind(kinds[1])}><span className="qicon">♙</span><div><b>Followers</b><small>Audience & members</small></div><ArrowRight size={14}/></button>
<button onClick={()=>setKind(kinds[2])}><span className="qicon">♥</span><div><b>Likes & reactions</b><small>Engagement services</small></div><ArrowRight size={14}/></button>
<button onClick={()=>setKind(kinds[4])}><span className="qicon">▶</span><div><b>Views</b><small>Video & content</small></div><ArrowRight size={14}/></button>
<button onClick={()=>setKind(kinds[3])}><span className="qicon">◌</span><div><b>Comments</b><small>Post interaction</small></div><ArrowRight size={14}/></button></div>
<div className="smm-catalog"><div className="smm-catalog-toolbar"><label className="smm-command-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by service name, keyword or ID"/></label><select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(x=><option key={x}>{x}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)}>{['All locations','Bangladesh','Worldwide','Mixed'].map(x=><option key={x}>{x}</option>)}</select></div>
<div className="smm-catalog-headrow"><span>AVAILABLE SERVICES</span><span>MIN / MAX</span><span>DELIVERY</span><span>REFILL</span><span>PRICE</span><span/></div>
{list===null?<div className="smm-service-list">{[1,2,3,4].map(i=><div className="smm-service-skeleton" key={i}/>)}</div>:loadError?<div className="smm-empty"><b>Catalogue unavailable</b><p>Please check the service database configuration.</p></div>:visible.length===0?<div className="smm-empty"><b>No services found</b><p>Try another platform or clear the filters.</p><button className="btn alt sm" onClick={()=>{setQ('');setPlatform(platforms[0]);setKind(kinds[0]);setCountry('All locations');}}>Reset marketplace</button></div>:<div className="smm-service-list">{displayed.map(s=><article className="smm-service-item" key={s.id}>
<div className="smm-service-name"><div className="smm-mini-icon">{s.smm_platform==='Instagram'?'◎':s.smm_platform==='Facebook'?'f':s.smm_platform==='TikTok'?'♪':s.smm_platform==='YouTube'?'▶':s.smm_platform==='Telegram'?'➤':'S'}</div><div><div className="smm-name-meta"><b>{s.smm_platform}</b><span>{s.smm_country||'Worldwide'}</span></div><h3>{s.name}</h3><p>{s.description||'Professional social media service.'}</p></div></div>
<div><small>MIN / MAX</small><b>{Number(s.smm_min_quantity||0).toLocaleString()} – {Number(s.smm_max_quantity||0).toLocaleString()}</b></div><div><small>DELIVERY</small><b>{s.smm_delivery_time||'—'}</b></div><div><small>REFILL</small><b>{s.smm_refill||'No'}</b></div><div className="smm-price"><small>PER 1K</small><strong>{taka(s.smm_price_per_1000)}</strong></div><button className="smm-buy" onClick={()=>beginOrder(s)}>Order <ArrowRight size={13}/></button></article>)}</div>}
{visible.length>9&&<button className="smm-more" onClick={()=>setShowMore(v=>!v)}>{showMore?'Show less':'View '+(visible.length-9)+' more services'}</button>}</div>
<div className="smm-footnote"><ShieldCheck size={15}/><span><b>Order safely.</b> Keep your target public during delivery. Every service follows its own start, delivery, refill and cancellation terms.</span></div></main></section></div>{selected&&</main></div>{selected&&</main>{selected&&<div className="smm-modal-back" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null);}}><section className="smm-modal" role="dialog" aria-modal="true" aria-labelledby="smm-order-title"><button className="smm-close" onClick={()=>setSelected(null)} aria-label="Close">×</button><span className="smm-overline">WALLET CHECKOUT</span><h2 id="smm-order-title">{selected.name}</h2><p className="muted">ID {selected.smm_service_code||'—'} · {selected.smm_platform} · {selected.smm_country}</p><div className="smm-modal-info">{selected.smm_instructions||'Submit a public link. Make sure the profile or content matches the chosen service.'}</div>{!session?<div className="smm-login-prompt"><b>Sign in to continue</b><p>Orders use your Stationery Dot Com account and wallet.</p><Link className="btn sm" to={`/account?next=${encodeURIComponent(`/smm?service=${selected.id}`)}`}>Sign in / create account <ArrowRight size={15}/></Link></div>:<form onSubmit={submit}><div className="smm-wallet-strip"><span><WalletCards size={16}/>Available wallet</span><b>{balance===null?'Loading…':taka(balance)}</b></div><label>Name<input name="name" defaultValue={profileName} required maxLength="120" autoComplete="name"/></label><label>Mobile number<input name="phone" required inputMode="tel" autoComplete="tel" placeholder="01XXXXXXXXX"/></label><label>Profile / post / channel link<input name="link" required type="url" placeholder="https://…"/></label><label>Quantity <small>({Number(selected.smm_min_quantity).toLocaleString()}–{Number(selected.smm_max_quantity).toLocaleString()})</small><input type="number" min={selected.smm_min_quantity} max={selected.smm_max_quantity} value={qty} onChange={e=>setQty(e.target.value)} required/></label><div className="smm-total"><span>Order total <small>Calculated and charged atomically on the server</small></span><b>{taka(total)}</b></div>{total>Number(balance||0)&&<div className="smm-insufficient">Insufficient balance. <Link to="/account#wallet">Add funds to your wallet</Link> before ordering.</div>}<label>Notes <small>(optional)</small><textarea name="notes" rows="2" maxLength="1000"/></label><label className="smm-consent"><input type="checkbox" name="agree" required/>I have read the service instructions and accept the listed delivery, refill and cancellation terms.</label>{message&&<p role="alert" className="err">{message}</p>}<button className="btn block" disabled={busy||balance===null||total>Number(balance||0)}>{busy?'Placing order…':'Confirm & place order'} <ArrowRight size={16}/></button></form>}</section></div>}</>;
}
