import {useEffect,useState} from 'react';import {Check,Loader2} from 'lucide-react';import {supabase,taka,getSettings} from '../lib/supabase';import StatusBadge from '../components/StatusBadge';import useTitle from '../lib/useTitle';import {waLink} from '../lib/whatsapp';
const STEPS=['Order placed','Payment confirmed','Processing','Completed'];
const NEXT={Pending:'We will review your order shortly.','Payment Pending':'We are waiting to verify your payment.','Payment Received':'Payment confirmed. Your order will start processing soon.',Processing:'We are working on your order.',Completed:'Your order is complete. Contact us if you need anything.',Cancelled:'This order was cancelled. Contact us if this is unexpected.',Refunded:'This order was refunded.'};
const idx=o=>o.status==='Completed'?3:o.status==='Processing'?2:(o.status==='Payment Received'||o.payment_status==='Paid')?1:0;
export default function TrackOrder(){const[s,setS]=useState({});useEffect(()=>{getSettings().then(setS);},[]);useTitle(s.tracking_heading||'Track Order',s.tracking_intro||'Track your order with your Order ID and phone number.');const[code,setCode]=useState('');const[phone,setPhone]=useState('');const[o,setO]=useState(null);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
async function go(e){e.preventDefault();setO(null);setMsg('');setBusy(true);const{data,error}=await supabase.rpc('track_order',{p_code:code,p_phone:phone});setBusy(false);if(error)return setMsg('Something went wrong. Please try again.');if(!data)return setMsg('No order found. Check your Order ID and phone number.');setO(data);}
const i=o?idx(o):0;const dead=o&&['Cancelled','Refunded'].includes(o.status);
return(<main className="track-page wrap" style={{maxWidth:760}}><div className="track-intro"><span className="section-overline">ORDER UPDATES</span><h1>{s.tracking_heading||'Track your order'}</h1><p>{s.tracking_intro||'Enter the Order ID and phone number used at checkout to see the latest update.'}</p></div><form className="card track-form" onSubmit={go}><label className="fld"><span>Order ID</span><input placeholder="STDC-YYYYMMDD-0123456789ABCDEF01234567" value={code} onChange={e=>setCode(e.target.value)} required/></label><label className="fld"><span>Phone number used for the order</span><input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} required/></label><button className="btn block" disabled={busy}>{busy?<Loader2 size={18} className="spin"/>:'Track Order'}</button></form>
{msg&&<p className="err" role="alert" style={{marginTop:12}}>{msg}</p>}
{o&&<div className="card tcard" style={{marginTop:16}}><div className="band"><div><div style={{fontSize:12,opacity:.7}}>ORDER ID</div><h3>{o.order_code}</h3></div><span>{new Date(o.created_at).toLocaleDateString()}</span></div><div className="pad"><p>{o.service_name} — {o.package_name} × {o.quantity}<br/><b>{taka(o.total)}</b></p><p>Order: <StatusBadge status={o.status}/> Payment: <StatusBadge status={o.payment_status}/></p>
{!dead&&<ol className="tl">{STEPS.map((s,k)=><li key={s} className={k<=i?(k===i?'now done':'done'):''}><span className="dot">{k<=i&&<Check size={14}/>}</span><span style={{paddingTop:3}}>{s}</span></li>)}</ol>}
<div className={'callout'+(dead?' warn':'')}><b>Next step:</b> {NEXT[o.status]}</div><a className="btn wa sm" style={{marginTop:12}} href={waLink('Order ID: '+o.order_code)}>Ask about this order</a></div></div>}</main>);}
