import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ShoppingCart,Star,Sparkles} from 'lucide-react';
import {taka} from '../lib/supabase';
import {waLink} from '../lib/whatsapp';
import {subscriptionDurationLabel} from '../lib/subscription';
import {addToCart} from '../pages/Cart';import {trackAddToCart} from '../lib/metaPixel';
export default function PackageCard({p,service}){ const [added,setAdded]=useState(false);
 const quoted=Number(p.price)<=0;const image=p.image_url||service?.image_url;
 return <article className={'card package-card'+(p.best_value?' package-best-value':'')}>{image&&<img className="package-card-image" src={image} alt={p.name}/>}<div className="package-card-heading"><div className="package-title-wrap"><h3>{p.name}</h3>{p.best_value&&<span className="package-best-badge"><Star size={11} fill="currentColor"/>Best Value</span>}</div>{p.access_type&&<span className="package-plan-badge">{p.access_type==='shared'?'Shared':'Personal'}</span>}</div><p className="muted package-card-description">{(p.description||'A clear, convenient option for this service.').split(/\\n|\n/).map((line,i)=><span key={i}>{line}{i < (p.description||'A clear, convenient option for this service.').split(/\\n|\n/).length-1 && <br/>}</span>)}</p>{p.access_type&&<div className="package-plan-details"><span>{p.access_type==='shared'?'Shared access':'Personal access'}</span><span>{subscriptionDurationLabel(p.duration_months)}</span></div>}<div className="package-card-price">{quoted?<><span className="price">Price on request</span><span className="muted">Final price agreed with our team</span></>:<><span className="price">{taka(p.price)}</span>{!p.access_type&&<span className="muted">{p.unit}</span>}</>}</div>{service.requires_file&&<p className="muted package-document-note">Documents required at checkout</p>}{quoted?<a className="btn wa block" href={waLink('Hello, I want to order '+service.name+' - '+p.name+'. Please confirm the requirements and final price.')} target="_blank" rel="noreferrer">Discuss &amp; order on WhatsApp</a>:<div className="package-actions"><button type="button" className="btn alt block" onClick={()=>{addToCart({id:p.id,name:p.name,service_name:service.name,price:p.price,unit:p.unit,access_type:p.access_type,duration_months:p.duration_months,requires_file:service.requires_file});trackAddToCart({contentId:p.id,contentName:p.name,value:Number(p.price),quantity:1});setAdded(true);window.setTimeout(()=>setAdded(false),1400)}}><ShoppingCart size={16}/>{added?'Added to cart':'Add to cart'}</button><Link className="btn block" to={'/order?service='+service.slug+'&package='+p.id}>Buy now</Link></div>}</article>;
}