import {useEffect,useState} from 'react';import {Routes,Route,Link,NavLink,Navigate,Outlet,useNavigate} from 'react-router-dom';import {supabase,isSupabaseConfigured,getSettings} from './lib/supabase';import BrandLogo from './components/BrandLogo';import {Activity,Boxes,ClipboardList,LayoutDashboard,LogOut,Package,Settings2,SlidersHorizontal,Users} from 'lucide-react';
import Navbar from './components/Navbar';import Footer from './components/Footer';import WhatsAppButton from './components/WhatsAppButton';
import Home from './pages/Home';import Services from './pages/Services';import ServiceDetails from './pages/ServiceDetails';import Order from './pages/Order';import OrderSuccess from './pages/OrderSuccess';import TrackOrder from './pages/TrackOrder';import Contact from './pages/Contact';import NotFound from './pages/NotFound';
import Account from './pages/Account';
import Privacy from './pages/Privacy';import Terms from './pages/Terms';
import Login from './pages/admin/Login';import Dashboard from './pages/admin/Dashboard';import Orders from './pages/admin/Orders';import OrderDetails from './pages/admin/OrderDetails';import AService from './pages/admin/Services';import APackages from './pages/admin/Packages';import Settings from './pages/admin/Settings';
import Content from './pages/admin/Content';import Customers from './pages/admin/Customers';
function Public(){return(<><Navbar/><Outlet/><Footer/><WhatsAppButton/></>);}
// UI gate only. Real protection is Row Level Security in the database (is_admin()).
function AdminGate(){const[st,setSt]=useState('load');const[brand,setBrand]=useState({});const nav=useNavigate();
useEffect(()=>{getSettings().then(setBrand).catch(()=>{});(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session)return setSt('no');const{data}=await supabase.from('admin_profiles').select('id').eq('id',session.user.id).maybeSingle();setSt(data?'yes':'denied');})();},[]);
if(st==='load')return <main className="wrap">Loading…</main>;if(st==='no')return <Navigate to="/admin/login" replace/>;
if(st==='denied')return <main className="wrap"><p className="err">This account is not an admin. See README step 3–4.</p><button className="btn" onClick={async()=>{await supabase.auth.signOut();nav('/admin/login');}}>Logout</button></main>;
const items=[[LayoutDashboard,'Overview','/admin'],[ClipboardList,'Orders','/admin/orders'],[Boxes,'Services','/admin/services'],[Package,'Packages & pricing','/admin/packages'],[Users,'Customers','/admin/customers'],[SlidersHorizontal,'Page content','/admin/content'],[Settings2,'Settings & payments','/admin/settings']];
return <div className="admin-shell"><aside className="admin-sidebar"><Link to="/admin" className="admin-brand"><BrandLogo src={brand.logo_url} name={brand.site_name||'Stationery Dot Com'}/><span><b>{brand.site_name||'Stationery Dot Com'}</b><small>STORE ADMIN</small></span></Link><div className="admin-nav-label">WORKSPACE</div><nav>{items.map(([I,label,to])=><NavLink end={to==='/admin'} to={to} key={to}><I size={18}/><span>{label}</span></NavLink>)}</nav><div className="admin-sidebar-bottom"><Link to="/" className="admin-view-site"><Activity size={17}/>View website</Link><button type="button" onClick={async()=>{await supabase.auth.signOut();nav('/admin/login');}}><LogOut size={17}/>Sign out</button></div></aside><main className="admin-main"><div className="admin-mobile-top"><b>{brand.site_name||'Stationery Dot Com'} · Admin</b><Link to="/">View site</Link></div><Outlet/></main></div>;}
export default function App(){const missing=!isSupabaseConfigured;return(<>{missing&&<div style={{background:'#fee2e2',color:'#991b1b',padding:10,textAlign:'center'}}>Supabase keys are missing (.env file). See README step 7.</div>}<Routes><Route element={<Public/>}><Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:slug" element={<ServiceDetails/>}/><Route path="/order" element={<Order/>}/><Route path="/order-success/:code" element={<OrderSuccess/>}/><Route path="/track-order" element={<TrackOrder/>}/><Route path="/contact" element={<Contact/>}/><Route path="/account" element={<Account/>}/><Route path="/privacy-policy" element={<Privacy/>}/><Route path="/terms-of-service" element={<Terms/>}/><Route path="*" element={<NotFound/>}/></Route>
<Route path="/admin/login" element={<Login/>}/><Route path="/admin" element={<AdminGate/>}><Route index element={<Dashboard/>}/><Route path="orders" element={<Orders/>}/><Route path="orders/:id" element={<OrderDetails/>}/><Route path="services" element={<AService/>}/><Route path="packages" element={<APackages/>}/><Route path="customers" element={<Customers/>}/><Route path="content" element={<Content/>}/><Route path="settings" element={<Settings/>}/></Route></Routes></>);}
