import {useEffect,useState} from 'react';import {Routes,Route,Link,Navigate,Outlet,useNavigate} from 'react-router-dom';import {supabase} from './lib/supabase';
import Navbar from './components/Navbar';import Footer from './components/Footer';import WhatsAppButton from './components/WhatsAppButton';
import Home from './pages/Home';import Services from './pages/Services';import ServiceDetails from './pages/ServiceDetails';import Order from './pages/Order';import OrderSuccess from './pages/OrderSuccess';import TrackOrder from './pages/TrackOrder';import Contact from './pages/Contact';import NotFound from './pages/NotFound';
import Login from './pages/admin/Login';import Dashboard from './pages/admin/Dashboard';import Orders from './pages/admin/Orders';import OrderDetails from './pages/admin/OrderDetails';import AService from './pages/admin/Services';import APackages from './pages/admin/Packages';import Settings from './pages/admin/Settings';
function Public(){return(<><Navbar/><Outlet/><Footer/><WhatsAppButton/></>);}
// UI gate only. Real protection is Row Level Security in the database (is_admin()).
function AdminGate(){const[st,setSt]=useState('load');const nav=useNavigate();
useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session)return setSt('no');const{data}=await supabase.from('admin_profiles').select('id').eq('id',session.user.id).maybeSingle();setSt(data?'yes':'denied');})();},[]);
if(st==='load')return <main className="wrap">Loading…</main>;if(st==='no')return <Navigate to="/admin/login" replace/>;
if(st==='denied')return <main className="wrap"><p className="err">This account is not an admin. See README step 3–4.</p><button className="btn" onClick={async()=>{await supabase.auth.signOut();nav('/admin/login');}}>Logout</button></main>;
return(<><nav className="nav"><div className="wrap"><b className="brand">Admin</b><div className="links"><Link to="/admin">Dashboard</Link><Link to="/admin/orders">Orders</Link><Link to="/admin/services">Services</Link><Link to="/admin/packages">Packages</Link><Link to="/admin/settings">Settings</Link><a href="#" onClick={async e=>{e.preventDefault();await supabase.auth.signOut();nav('/admin/login');}}>Logout</a></div></div></nav><main className="wrap"><Outlet/></main></>);}
export default function App(){const missing=!import.meta.env.VITE_SUPABASE_URL||!import.meta.env.VITE_SUPABASE_ANON_KEY;return(<>{missing&&<div style={{background:'#fee2e2',color:'#991b1b',padding:10,textAlign:'center'}}>Supabase keys are missing (.env file). See README step 7.</div>}<Routes><Route element={<Public/>}><Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:slug" element={<ServiceDetails/>}/><Route path="/order" element={<Order/>}/><Route path="/order-success/:code" element={<OrderSuccess/>}/><Route path="/track-order" element={<TrackOrder/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Route>
<Route path="/admin/login" element={<Login/>}/><Route path="/admin" element={<AdminGate/>}><Route index element={<Dashboard/>}/><Route path="orders" element={<Orders/>}/><Route path="orders/:id" element={<OrderDetails/>}/><Route path="services" element={<AService/>}/><Route path="packages" element={<APackages/>}/><Route path="settings" element={<Settings/>}/></Route></Routes></>);}
