import {useEffect,useState} from 'react';import {ExternalLink,Eye,EyeOff,Save} from 'lucide-react';import {Link} from 'react-router-dom';import {supabase,getSettings} from '../../lib/supabase';
const sections=[
{title:'Hero section',hint:'The first block visitors see on the home page.',fields:[['home_kicker','Small heading'],['hero_title','Main heading'],['hero_highlight','Highlighted words'],['hero_description','Introduction'],['home_trust_1','Trust point 1'],['home_trust_2','Trust point 2'],['home_trust_3','Trust point 3']]},
{title:'Announcement bar',hint:'Leave blank to hide the narrow bar above the page.',fields:[['announcement','Announcement text']]},
{title:'Service categories',hint:'Categories are built from active services. Set or add a category on the Services page.',visibleKey:'home_visibility_categories',fields:[['home_categories_title','Section heading'],['home_categories_copy','Section description']]},
{title:'Featured services',hint:'Choose featured services on the Services page using “Show as popular”.',visibleKey:'home_visibility_featured',fields:[['home_featured_title','Section heading'],['home_featured_copy','Section description']]},
{title:'Why choose us',hint:'Four reasons shown as feature cards.',visibleKey:'home_visibility_benefits',fields:[['home_benefits_title','Section heading'],['home_benefit_1_title','Card 1 heading'],['home_benefit_1_copy','Card 1 text'],['home_benefit_2_title','Card 2 heading'],['home_benefit_2_copy','Card 2 text'],['home_benefit_3_title','Card 3 heading'],['home_benefit_3_copy','Card 3 text'],['home_benefit_4_title','Card 4 heading'],['home_benefit_4_copy','Card 4 text']]},
{title:'How it works',hint:'The five ordering steps on the home page.',visibleKey:'home_visibility_steps',fields:[['home_steps_title','Section heading'],['home_step_1','Step 1 heading'],['home_step_1_copy','Step 1 description'],['home_step_2','Step 2 heading'],['home_step_2_copy','Step 2 description'],['home_step_3','Step 3 heading'],['home_step_3_copy','Step 3 description'],['home_step_4','Step 4 heading'],['home_step_4_copy','Step 4 description'],['home_step_5','Step 5 heading'],['home_step_5_copy','Step 5 description']]},
{title:'Closing banner',hint:'The final call-to-action at the bottom of the home page.',visibleKey:'home_visibility_cta',fields:[['home_cta_title','Heading'],['home_cta_copy','Supporting text']]},
{title:'Service catalogue page',hint:'The main heading and intro at the top of the service list.',fields:[['catalog_title','Page heading'],['catalog_intro','Introduction']]},
{title:'Order tracking page',hint:'Tell customers what they need to look up an order.',fields:[['tracking_heading','Page heading'],['tracking_intro','Introduction']]},
{title:'Contact page',hint:'Heading, introduction and opening hours. Phone and address are in Settings.',fields:[['contact_heading','Page heading'],['contact_intro','Introduction'],['contact_hours','Opening hours']]}
];
const multi=new Set(['hero_description','home_categories_copy','home_featured_copy','home_benefit_1_copy','home_benefit_2_copy','home_benefit_3_copy','home_benefit_4_copy','home_step_1_copy','home_step_2_copy','home_step_3_copy','home_step_4_copy','home_step_5_copy','home_cta_copy','catalog_intro','tracking_intro','contact_intro']);
export default function Content(){const[s,setS]=useState({});const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{getSettings().then(setS);},[]);const change=(k,v)=>setS(x=>({...x,[k]:v}));async function save(e){e.preventDefault();setBusy(true);setMsg('');const rows=sections.flatMap(g=>[...g.fields.map(([key])=>({key,value:s[key]||''})),...(g.visibleKey?[{key:g.visibleKey,value:s[g.visibleKey]||'true'}]:[])]);const{error}=await supabase.from('site_settings').upsert(rows);setBusy(false);setMsg(error?error.message:'Home page sections saved.');}
return <div className="content-admin"><div className="admin-heading"><div><span className="eyebrow">Page builder</span><h1>Page content</h1><p className="muted">Edit customer-facing pages section by section. Hide or show optional home page sections.</p></div><Link className="btn alt" to="/"><ExternalLink size={16}/>Preview website</Link></div><form onSubmit={save}>{sections.map((group,i)=><section className="content-section" key={group.title}><div className="content-section-title"><div><h2>{group.title}</h2><p>{group.hint}</p></div>{group.visibleKey?<label className="section-toggle"><input type="checkbox" checked={s[group.visibleKey]!=='false'} onChange={e=>change(group.visibleKey,e.target.checked?'true':'false')}/>{s[group.visibleKey]==='false'?<><EyeOff size={14}/>Hidden</>:<><Eye size={14}/>Shown</>}</label>:<span>0{i+1}</span>}</div><div className="content-fields">{group.fields.map(([key,label])=><label key={key}>{label}{multi.has(key)?<textarea rows={3} value={s[key]||''} onChange={e=>change(key,e.target.value)}/>:<input value={s[key]||''} onChange={e=>change(key,e.target.value)}/>}</label>)}</div></section>)}<div className="content-save"><button className="btn" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save page content'}</button>{msg&&<span role="status" className={msg.includes('saved')?'ok':'err'}>{msg}</span>}</div></form></div>;
}
