import {useEffect,useState} from 'react';
import {Plus,Trash2,Tag} from 'lucide-react';
import {supabase,taka} from '../../lib/supabase';

const fresh=()=>({code:'',discount_type:'percent',discount_value:'',min_order:'0',max_discount:'',usage_limit:'',starts_at:'',expires_at:'',is_active:true});
export default function Coupons(){
 const[rows,setRows]=useState(null),[form,setForm]=useState(fresh()),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const{data,error}=await supabase.from('coupons').select('*').order('created_at',{ascending:false});if(error)setMsg(error.message);setRows(data||[]);}
 useEffect(()=>{load()},[]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(e){e.preventDefault();setMsg('');const code=form.code.trim().toUpperCase();if(!code)return setMsg('Coupon code is required.');if(Number(form.discount_value)<=0)return setMsg('Discount value must be greater than 0.');setBusy(true);
  const row={code,discount_type:form.discount_type,discount_value:Number(form.discount_value),min_order:Number(form.min_order||0),max_discount:form.max_discount===''?null:Number(form.max_discount),usage_limit:form.usage_limit===''?null:Number(form.usage_limit),starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,expires_at:form.expires_at?new Date(form.expires_at).toISOString():null,is_active:form.is_active};
  const{error}=await supabase.from('coupons').insert(row);setBusy(false);if(error)return setMsg(error.message);setMsg('Coupon created.');setForm(fresh());load();
 }
 async function toggle(x){const{error}=await supabase.from('coupons').update({is_active:!x.is_active}).eq('id',x.id);setMsg(error?.message||(x.is_active?'Coupon disabled.':'Coupon enabled.'));load();}
 async function remove(x){if(!confirm('Delete this coupon?'))return;const{error}=await supabase.from('coupons').delete().eq('id',x.id);setMsg(error?.message||'Coupon deleted.');load();}
 return <div className="coupon-admin"><header className="admin-heading"><div><span className="eyebrow">Offers & discounts</span><h1>Coupons</h1><p className="muted">Create percentage or fixed discounts for customer checkout.</p></div></header>
 {msg&&<p className="ok" role="status">{msg}</p>}
 <form className="card coupon-editor" onSubmit={save}><div className="panel-title"><span className="account-icon"><Tag size={19}/></span><div><h2>Create coupon</h2><p>Coupon codes are validated again on the server when an order is placed.</p></div></div>
 <div className="content-fields"><label>Code<input value={form.code} onChange={e=>set('code',e.target.value.toUpperCase())} placeholder="WELCOME50" maxLength={40} required/></label><label>Discount type<select value={form.discount_type} onChange={e=>set('discount_type',e.target.value)}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Discount value<input type="number" min="0.01" step="0.01" value={form.discount_value} onChange={e=>set('discount_value',e.target.value)} required/></label><label>Minimum order (৳)<input type="number" min="0" step="0.01" value={form.min_order} onChange={e=>set('min_order',e.target.value)}/></label><label>Max discount (৳)<input type="number" min="0" step="0.01" value={form.max_discount} onChange={e=>set('max_discount',e.target.value)} placeholder="Optional"/></label><label>Usage limit<input type="number" min="1" step="1" value={form.usage_limit} onChange={e=>set('usage_limit',e.target.value)} placeholder="Unlimited"/></label><label>Starts<input type="datetime-local" value={form.starts_at} onChange={e=>set('starts_at',e.target.value)}/></label><label>Expires<input type="datetime-local" value={form.expires_at} onChange={e=>set('expires_at',e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={form.is_active} onChange={e=>set('is_active',e.target.checked)}/> Active</label></div>
 <button className="btn" disabled={busy}><Plus size={16}/>{busy?'Creating…':'Create coupon'}</button></form>
 <section className="coupon-list"><h2>Existing coupons</h2>{rows===null?<div className="sk"/>:rows.length?<div className="grid">{rows.map(x=><article className="card coupon-card" key={x.id}><div className="coupon-card-top"><b>{x.code}</b><span className={x.is_active?'service-status visible':'service-status'}>{x.is_active?'Active':'Disabled'}</span></div><strong>{x.discount_type==='percent'?x.discount_value+'%':taka(x.discount_value)} off</strong><p className="muted">Min order {taka(x.min_order)} · Used {x.used_count}{x.usage_limit?' / '+x.usage_limit:' times'}</p>{x.expires_at&&<small>Expires {new Date(x.expires_at).toLocaleString()}</small>}<div className="row" style={{marginTop:12}}><button type="button" className="btn sm alt" onClick={()=>toggle(x)}>{x.is_active?'Disable':'Enable'}</button><button type="button" className="btn sm red" onClick={()=>remove(x)}><Trash2 size={14}/>Delete</button></div></article>)}</div>:<div className="card empty">No coupons yet.</div>}</section>
 </div>;
}
