import {useEffect,useState} from 'react';import {useParams} from 'react-router-dom';import {supabase,taka,ORDER_STATUSES,PAY_STATUSES} from '../../lib/supabase';
export default function OrderDetails(){const{id}=useParams();const[o,setO]=useState(null);const[urls,setUrls]=useState([]);const[m,setM]=useState('');
const load=async()=>{const{data}=await supabase.from('orders').select('*,payments(*),order_files(*)').eq('id',id).single();setO(data);const u=[];for(const f of data?.order_files||[]){const{data:s}=await supabase.storage.from('order-files').createSignedUrl(f.file_path,300);u.push({name:f.file_name,url:s?.signedUrl});}setUrls(u);};
useEffect(()=>{load();},[id]);if(!o)return 'Loading…';const pay=o.payments?.[0];
const setStatus=async v=>{const{error}=await supabase.from('orders').update({status:v,updated_at:new Date().toISOString()}).eq('id',id);setM(error?error.message:'Order status saved');load();};
const setPay=async v=>{const{error}=await supabase.from('payments').update({status:v}).eq('id',pay.id);if(!error&&v==='Paid'&&['Pending','Payment Pending'].includes(o.status))await supabase.from('orders').update({status:'Payment Received',updated_at:new Date().toISOString()}).eq('id',id);setM(error?error.message:'Payment status saved');load();};
return(<><h1>{o.order_code}</h1><div className="card"><p><b>{o.customer_name}</b><br/>Phone: <a href={`tel:${o.phone}`}>{o.phone}</a> · WhatsApp: {o.whatsapp||'—'} · Email: {o.email||'—'}</p><p>{o.service_name} — {o.package_name} × {o.quantity} = <b>{taka(o.total)}</b></p><p>Notes: {o.notes||'—'}</p>
<p>Payment: {pay?.method} · via {pay?.provider||'manual'}{pay?.provider_ref?` · Ref ${pay.provider_ref}`:''}{pay?.paid_at?` · auto-paid ${new Date(pay.paid_at).toLocaleString()}`:''} · Txn ID: <b>{pay?.transaction_id}</b> · Amount {taka(pay?.amount)}</p><p>Files: {urls.length?urls.map((u,i)=><a key={i} href={u.url} target="_blank" rel="noreferrer" style={{marginRight:8,textDecoration:'underline'}}>{u.name}</a>):'none'}</p></div>
<label>Order status</label><select value={o.status} onChange={e=>setStatus(e.target.value)}>{ORDER_STATUSES.map(s=><option key={s}>{s}</option>)}</select>
<label>Payment status</label><select value={pay?.status} onChange={e=>setPay(e.target.value)}>{PAY_STATUSES.map(s=><option key={s}>{s}</option>)}</select>{m&&<p className="ok">{m}</p>}</>);}
