import {useEffect,useState} from 'react';import {supabase,taka} from '../../lib/supabase';
const blank={service_id:'',name:'',description:'',price:'',unit:'per order',is_active:true,sort_order:0};
export default function Packages(){const[sv,setSv]=useState([]);const[l,setL]=useState([]);const[f,setF]=useState(blank);const[m,setM]=useState('');
const load=async()=>{setSv((await supabase.from('services').select('id,name').order('name')).data||[]);setL((await supabase.from('packages').select('*,services(name)').order('created_at',{ascending:false})).data||[]);};useEffect(()=>{load();},[]);
const save=async e=>{e.preventDefault();const{services,...row}=f;row.price=Number(row.price);if(!row.service_id)return setM('Choose a service');const{error}=await supabase.from('packages').upsert(row);setM(error?error.message:'Saved');setF(blank);load();};
const del=async id=>{if(confirm('Delete this package?')){const{error}=await supabase.from('packages').delete().eq('id',id);setM(error?error.message:'Deleted');load();}};const up=(k,v)=>setF({...f,[k]:v});
return(<><h1>Packages &amp; Pricing</h1>{m&&<p className="ok">{m}</p>}<form onSubmit={save} className="card"><label>Service</label><select value={f.service_id} onChange={e=>up('service_id',e.target.value)}><option value="">Select…</option>{sv.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>
<label>Package name</label><input value={f.name} onChange={e=>up('name',e.target.value)} required/><label>Description</label><input value={f.description||''} onChange={e=>up('description',e.target.value)}/><label>Price (৳)</label><input type="number" min="0" step="0.01" value={f.price} onChange={e=>up('price',e.target.value)} required/><label>Unit (e.g. per order, per 1000)</label><input value={f.unit} onChange={e=>up('unit',e.target.value)}/>
<label><input type="checkbox" style={{width:'auto'}} checked={f.is_active} onChange={e=>up('is_active',e.target.checked)}/> Active</label><p><button className="btn">{f.id?'Update':'Add'} package</button></p></form>
<div className="scroll"><table><tbody>{l.map(p=><tr key={p.id}><td>{p.services?.name}<br/><b>{p.name}</b></td><td>{taka(p.price)} {p.unit}</td><td>{p.is_active?'Active':'Hidden'}</td><td><button className="btn sm alt" onClick={()=>{setF(p);window.scrollTo(0,0);}}>Edit</button> <button className="btn sm red" onClick={()=>del(p.id)}>Delete</button></td></tr>)}</tbody></table></div></>);}
