import {useEffect,useState} from 'react';import {supabase} from '../../lib/supabase';import {CATEGORIES,STARTER_SERVICES} from '../../data/services';
const blank={category:CATEGORIES[0].name,name:'',slug:'',description:'',requires_file:false,is_popular:false,is_active:true,sort_order:0};
export default function Services(){const[l,setL]=useState([]);const[f,setF]=useState(blank);const[m,setM]=useState('');const load=()=>supabase.from('services').select('*').order('sort_order').then(r=>setL(r.data||[]));useEffect(()=>{load();},[]);
const save=async e=>{e.preventDefault();const row={...f,slug:f.slug||f.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')};const{error}=await supabase.from('services').upsert(row);setM(error?error.message:'Saved');setF(blank);load();};
const seed=async()=>{const{error}=await supabase.from('services').upsert(STARTER_SERVICES,{onConflict:'slug',ignoreDuplicates:true});setM(error?error.message:'Starter services added');load();};
const up=(k,v)=>setF({...f,[k]:v});
const img=async e=>{const x=e.target.files[0];if(!x)return;if(!['image/jpeg','image/png','image/webp'].includes(x.type)||x.size>2*1024*1024)return setM('Image must be jpg/png/webp, max 2MB');const path=`services/${crypto.randomUUID()}-${x.name.replace(/[^\w.\-]/g,'_')}`;const{error}=await supabase.storage.from('site-assets').upload(path,x);if(error)return setM(error.message);setF({...f,image_url:supabase.storage.from('site-assets').getPublicUrl(path).data.publicUrl});setM('Image uploaded. Click Add/Update service to save.');};
return(<><h1>Services</h1><button className="btn alt" onClick={seed}>Import starter services list</button>{m&&<p className="ok">{m}</p>}
<form onSubmit={save} className="card" style={{margin:'12px 0'}}><label>Category <span className="muted">(type a current category or add a new one)</span></label><input value={f.category} onChange={e=>up('category',e.target.value)} list="service-categories" required/><datalist id="service-categories">{CATEGORIES.map(c=><option key={c.name} value={c.name}/>)}</datalist><label>Name</label><input value={f.name} onChange={e=>up('name',e.target.value)} required/><label>Description</label><textarea value={f.description||''} onChange={e=>up('description',e.target.value)}/><label>Display order (smaller numbers show first)</label><input type="number" value={f.sort_order??0} onChange={e=>up('sort_order',Number(e.target.value))}/>
<label>Cover image (16:9 works best; jpg/png/webp, max 2MB; needs service-images.sql)</label>{f.image_url&&<img src={f.image_url} alt="" style={{width:200,aspectRatio:'16/9',objectFit:'cover',borderRadius:10,display:'block',marginBottom:8}}/>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={img}/>{f.image_url&&<p><button type="button" className="btn sm alt" onClick={()=>setF({...f,image_url:null})}>Remove image</button></p>}<label><input type="checkbox" style={{width:'auto'}} checked={f.requires_file} onChange={e=>up('requires_file',e.target.checked)}/> Customer must upload documents</label><label><input type="checkbox" style={{width:'auto'}} checked={f.is_popular} onChange={e=>up('is_popular',e.target.checked)}/> Show as popular</label><label><input type="checkbox" style={{width:'auto'}} checked={f.is_active} onChange={e=>up('is_active',e.target.checked)}/> Active (visible)</label><p><button className="btn">{f.id?'Update':'Add'} service</button></p></form>
<div className="scroll"><table><tbody>{l.map(s=><tr key={s.id}><td>{s.image_url&&<img className="thumb" src={s.image_url} alt=""/>}{s.name}<br/><span className="muted">{s.category}</span></td><td>{s.is_active?'Active':'Hidden'}{s.is_popular&&' · Popular'}</td><td><button className="btn sm alt" onClick={()=>{setF(s);window.scrollTo(0,0);}}>Edit</button></td></tr>)}</tbody></table></div></>);}
