import {useEffect,useState} from 'react';import {supabase,getSettings,isPdf} from '../../lib/supabase';
const F=[['site_name','Website name'],['site_tagline','Short tagline'],['announcement','Announcement banner (leave empty to hide)'],['hero_title','Home page main heading'],['hero_highlight','Home page highlighted words'],['hero_description','Home page introduction'],['footer_description','Footer description'],['contact_address','Contact address'],['contact_phone','Primary phone number'],['contact_phone_2','Second phone number'],['contact_whatsapp','WhatsApp number (international digits, e.g. 8801...)'],['payment_method_name','Payment method name (e.g. bKash Merchant QR)'],['payment_account_name','Account / payment name'],['payment_number','Payment number / account'],['payment_instructions','Payment instructions']];
export default function Settings(){const[s,setS]=useState({});const[m,setM]=useState('');useEffect(()=>{getSettings().then(setS);},[]);
const save=async()=>{const rows=Object.entries(s).map(([key,value])=>({key,value}));const{error}=await supabase.from('site_settings').upsert(rows);setM(error?error.message:'Settings saved');};
const QR_MIME={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',pdf:'application/pdf'};
const qr=async e=>{const x=e.target.files[0];if(!x)return;const ext=x.name.split('.').pop().toLowerCase();const type=QR_MIME[ext];if(!type)return setM('Allowed: PDF, JPG, PNG, WEBP');if(x.size>10*1024*1024)return setM('File must be 10MB or smaller');const path=`qr-${Date.now()}.${ext}`;const{error}=await supabase.storage.from('site-assets').upload(path,x,{contentType:type});if(error)return setM(/mime|type/i.test(error.message)?'This file type is not enabled yet. Run supabase/qr-pdf-support.sql in Supabase first.':error.message);const{data}=supabase.storage.from('site-assets').getPublicUrl(path);setS({...s,payment_qr_url:data.publicUrl});setM('QR uploaded. Now click Save settings.');};
return(<><h1>Site &amp; Payment Settings</h1><p className="muted">Control the public home page, contact details and payment instructions from here.</p><form className="card admin-settings" onSubmit={e=>{e.preventDefault();save();}}><h2>Website content</h2>{F.slice(0,11).map(([k,l])=><div key={k}><label>{l}</label>{['announcement','hero_description','footer_description','contact_address'].includes(k)?<textarea rows={k==='hero_description'?3:2} value={s[k]||''} onChange={e=>setS({...s,[k]:e.target.value})}/>:<input value={s[k]||''} onChange={e=>setS({...s,[k]:e.target.value})}/>}</div>)}<h2>Payment details</h2>{F.slice(11).map(([k,l])=><div key={k}><label>{l}</label>{k==='payment_instructions'?<textarea rows="3" value={s[k]||''} onChange={e=>setS({...s,[k]:e.target.value})}/>:<input value={s[k]||''} onChange={e=>setS({...s,[k]:e.target.value})}/>}</div>)}
<label>Payment QR (PDF, JPG, PNG or WEBP, max 10MB)</label><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/*" onChange={qr}/>{s.payment_qr_url&&(isPdf(s.payment_qr_url)?<p><a className="btn alt sm" href={s.payment_qr_url} target="_blank" rel="noopener noreferrer">Current QR: PDF (open to check)</a></p>:<img src={s.payment_qr_url} alt="QR" style={{maxWidth:200,display:'block',marginTop:8}}/>)}
<p><button className="btn">Save all settings</button></p>{m&&<p className="ok" role="status">{m}</p>}<p className="callout warn">Automatic transaction verification needs a bKash/Nagad merchant API account and provider credentials. Until those are configured, submitted transaction IDs stay in “Verification Pending” for admin review.</p></form></>);}
