import {useEffect,useState} from 'react';import {ExternalLink} from 'lucide-react';import {supabase,getSettings,isPdf} from '../../lib/supabase';
const siteFields=[['site_name','Website name'],['site_tagline','Short tagline'],['footer_description','Footer description'],['contact_address','Business address'],['contact_phone','Main phone'],['contact_phone_2','Second phone'],['contact_whatsapp','WhatsApp number (international digits, e.g. 8801...)']];
const QR_MIME={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',pdf:'application/pdf'};
export default function Settings(){const[s,setS]=useState({});const[m,setM]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{getSettings().then(setS);},[]);const set=(key,value)=>setS(x=>({...x,[key]:value}));
async function save(e){e.preventDefault();setBusy(true);setM('');const rows=Object.entries(s).map(([key,value])=>({key,value:value??''}));const{error}=await supabase.from('site_settings').upsert(rows);setBusy(false);setM(error?error.message:'Settings saved.');}
async function qr(e,key){const x=e.target.files?.[0];if(!x)return;const ext=x.name.split('.').pop().toLowerCase(),type=QR_MIME[ext];if(!type)return setM('Allowed: PDF, JPG, PNG, WEBP');if(x.size>10*1024*1024)return setM('File must be 10MB or smaller');const path=`qr-${key}-${Date.now()}.${ext}`;const{error}=await supabase.storage.from('site-assets').upload(path,x,{contentType:type});if(error)return setM(error.message);const{data}=supabase.storage.from('site-assets').getPublicUrl(path);set(key,data.publicUrl);setM('QR uploaded. Save settings to publish it.');}
const fileInput=(label,key)=><label key={key}>{label}<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/*" onChange={e=>qr(e,key)}/>{s[key]&&(isPdf(s[key])?<a className="btn alt sm" href={s[key]} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/> Open current QR</a>:<img src={s[key]} alt="Current payment QR" className="settings-qr-preview"/>)}</label>;
return <div className="settings-admin"><div className="admin-heading"><div><span className="eyebrow">Store configuration</span><h1>Settings &amp; payments</h1><p className="muted">Manage contact details and the manual bKash/Nagad checkout instructions.</p></div></div><form onSubmit={save}><section className="content-section"><div className="content-section-title"><div><h2>Business details</h2><p>Brand name, public contact and footer information.</p></div><span>GENERAL</span></div><div className="content-fields">{siteFields.map(([key,label])=><label key={key}>{label}{['footer_description','contact_address'].includes(key)?<textarea rows={3} value={s[key]||''} onChange={e=>set(key,e.target.value)}/>:<input value={s[key]||''} onChange={e=>set(key,e.target.value)}/>}</label>)}</div></section><section className="content-section"><div className="content-section-title"><div><h2>Payment channels</h2><p>Only fill in payment accounts owned by your business. Customers see each channel you configure.</p></div><span>CHECKOUT</span></div><div className="content-fields"><label>bKash account number<input inputMode="tel" value={s.payment_bkash_number||''} onChange={e=>set('payment_bkash_number',e.target.value)} placeholder="01XXXXXXXXX"/></label><label>Nagad account number<input inputMode="tel" value={s.payment_nagad_number||''} onChange={e=>set('payment_nagad_number',e.target.value)} placeholder="01XXXXXXXXX"/></label><label>Account holder / business name<input value={s.payment_account_name||''} onChange={e=>set('payment_account_name',e.target.value)}/></label><label>Payment instructions<textarea rows={4} value={s.payment_instructions||''} onChange={e=>set('payment_instructions',e.target.value)} placeholder="Send the exact order total, then enter the Transaction ID from your receipt."/></label>{fileInput('bKash QR (PDF, JPG, PNG or WEBP, max 10MB)','payment_bkash_qr_url')}{fileInput('Nagad QR (PDF, JPG, PNG or WEBP, max 10MB)','payment_nagad_qr_url')}{fileInput('Shared QR (optional)','payment_qr_url')}<label>Optional shared payment number<input inputMode="tel" value={s.payment_number||''} onChange={e=>set('payment_number',e.target.value)} placeholder="Use when one number supports both methods"/></label><p className="callout warn form-wide">These are manual Send Money/payment instructions. An entered Transaction ID stays <b>Verification Pending</b> until an admin confirms it. Automatic confirmation needs your official merchant/gateway API credentials and provider verification setup.</p></div></section><div className="content-save"><button className="btn" disabled={busy}>{busy?'Saving…':'Save settings'}</button>{m&&<span role="status" className={m.includes('saved')||m.includes('uploaded')?'ok':'err'}>{m}</span>}</div></form></div>;
}
